### ISSUE TITLE
提案

### ISSUE THREAD

**Issue by henji243** [pscore23/voify#3]
(今のところバグは見られないので、改善したほうがよさそうな点を言っておきます)

- インストールしているライブラリによっては見にくくなるため、スクロールバーなどで見やすくする
- 存在しないモジュールを指定したときのメッセージ

![cache_b257a0d5-1878-4424-c4b1-4b92e0661a7c](https://user-images.githubusercontent.com/105550500/194561821-64db3fc6-8f50-49d3-8c84-b52607271aee.png)

**Comment by pscore23** [comment]
ありがとうございます!
v1.0.1a1 で
`存在しないモジュールを指定したときのメッセージ` を追加します

**Comment by pscore23** [comment]
「存在しないモジュールを指定したときのメッセージ」を #4 で実装し、master ブランチにマージしました。
「インストールしているライブラリによっては見にくくなるため、スクロールバーなどで見やすくする」も v1.0.2a1 で実装する予定です...

**Comment by pscore23** [comment]
(ちなみに、赤色で表示されてるライブラリはアップデート可能って意味です)

**Comment by pscore23** [comment]
「インストールしているライブラリによっては見にくくなるため、スクロールバーなどで見やすくする」を [このコミット](https://github.com/pscore23/voify/commit/1225fe0e441af1341d06e3af1bc26f5d0dffb2ac) で実装し、master ブランチにプッシュしました。

**Comment by henji243** [comment]
お～爆速実装お疲れ様です!

**Comment by pscore23** [comment]
ありがとうございます((
