### ISSUE TITLE
バグ報告

### ISSUE THREAD

**Issue by henji243** [pscore23/voify#5]
起動時、ウィンドウのサイズがこっちの環境では少し小さいので、
サイズの設定を、710x860ぐらいにするとよくなりました。
![image](https://user-images.githubusercontent.com/105550500/194786669-fe6d519e-b184-4432-a288-b6464125bfa6.png)
↑最初

それと、こっちの環境ではなぜかインストールができません。
1.0.0a1のほうではできました。(下の画像では、一旦Seleniumをアンインストールしてから試しています。)
![image](https://user-images.githubusercontent.com/105550500/194787318-86bf3fe7-b84b-4af8-9a96-d2d523b2682a.png)

**Comment by pscore23** [comment]
ありがとうございます!
原因を調査中です...

**Comment by pscore23** [comment]
インストールが出来ない問題を [このコミット](https://github.com/pscore23/voify/commit/32ecf50587fb618187762f47d207b44daae170f7) で修正しました。
ウィンドウのサイズについては、OS やディスプレイの設定で挙動が違うみたいなので、修正は出来ないと判断しました。
端の方をドラッグすると一応ウィンドウのサイズは変えられるようにしましたが、レイアウトがそれに合わせてサイズが変わらないので実用的ではないですね...
